theme: jekyll-theme-minimal
logo: /images/me.jpg
google_analytics: UA-150479065-2
title: Elyes Manai
description: Google Developer Expert in Machine Learning loking to pursue a Ph.D in robustness, fairness and/or efficiency learning in Machine learning.

